version: "3"
services:
    frontend:
        build: frontend
        restart: always
        ports:
            - "80:8080"
        depends_on:
            - backend
    backend:
        build: backend
        restart: always
        ports:
            - "5000:5000"
        volumes:
            - ./backend:/usr/src/app
    redis:
        image: redis
        restart: always
